apiVersion: v1
kind: Service
metadata:
  name: forgestatus-dashboard-service-${ENV}
spec:
  type: NodePort
  selector:
    app: forgestatus-dashboard-${ENV}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
